function t = table(obj)
%TABLE Overloads table converter method
%   Returns a table of timeseries properties

varNames = { ...
    'Time', ...
    'RedCounts', ...
    'GreenCounts', ...
    'BlueCounts', ...
    'ActivityIndexCounts'};

t = table( ...
    obj.Time, ...
    obj.RedCounts, ...
    obj.GreenCounts, ...
    obj.BlueCounts, ...
    obj.ActivityIndexCounts, ...
    'VariableNames',varNames);

end

