function t = table(obj)
%TABLE Overloads table converter method
%   Returns a table of timeseries properties

varNames = { ...
    'Time', ...
    'Resets', ...
    'RedCounts', ...
    'GreenCounts', ...
    'BlueCounts', ...
    'ActivityIndexCounts', ...
    'Red', ...
    'Green', ...
    'Blue', ...
    'ActivityIndex'};

t = table( ...
    obj.Time, ...
    obj.Resets, ...
    obj.RedCounts, ...
    obj.GreenCounts, ...
    obj.BlueCounts, ...
    obj.ActivityIndexCounts, ...
    obj.Red, ...
    obj.Green, ...
    obj.Blue, ...
    obj.ActivityIndex, ...
    'VariableNames',varNames);

end

