function [analysisStartTime,analysisEndTime,bedTime,wakeTime] = importSleepLog(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [analysisStartTime,analysisEndTime,bedTime,wakeTime] = IMPORTFILE(FILE)
%   reads data from the first worksheet in the Microsoft Excel spreadsheet
%   file named FILE and returns the data as column vectors.
%
%   [analysisStartTime,analysisEndTime,bedTime,wakeTime] =
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [analysisStartTime,analysisEndTime,bedTime,wakeTime] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Date formatted cells are converted to MATLAB serial date number format
%	(datenum).
%
% Example:
%   [analysisStartTime,analysisEndTime,bedTime,wakeTime] =
%   importfile('testSleepLog.xlsx','Sheet1',2,4);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2014/02/10 16:34:38
import sleep.*

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 4;
end

%% Import the data, extracting spreadsheet dates in MATLAB serial date number format (datenum)
[~, ~, raw, dateNums] = xlsread(workbookFile, sheetName, sprintf('A%d:D%d',startRow(1),endRow(1)),'' , @convertSpreadsheetDates);
for block=2:length(startRow)
    [~, ~, tmpRawBlock,tmpDateNumBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:D%d',startRow(block),endRow(block)),'' , @convertSpreadsheetDates);
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
    dateNums = [dateNums;tmpDateNumBlock]; %#ok<AGROW>
end

%% Replace date strings by MATLAB serial date numbers (datenum)
R = ~cellfun(@isequalwithequalnans,dateNums,raw) & cellfun('isclass',raw,'char'); % Find spreadsheet dates
raw(R) = dateNums(R);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
analysisStartTime = data(:,1);
analysisEndTime = data(:,2);
bedTime = data(:,3);
wakeTime = data(:,4);

