function [ paths ] = initPaths(project, experiment, root)
%INITPATHS Gathers the paths for the diffrent folders needed for a Project
%   This look in the root projects folder or the folder that you pass to it
%   to gather folder locations so that it becomes easier to program and use
%   the folders. 
% 
%   Project:    this should be the parent folder for all the data files.
%               this will be the main folder that the program spends it 
%               time in, finding all the important filles off of this. 
%
%   Experiment: This should be the interation of the project that you want
%               want to pull the data for. 
%
%   Root:       This the folder where the project folder is located, if
%               this is omitted then the program will use \\ROOT\Projects
%               as the default selection. 


if nargin == 2
    root= fullfile([filesep,filesep],'root','projects');
end
paths = struct(...
    'project'           ,fullfile(root,project),...
    'Logistics'         ,fullfile(root,project,'Logistics'),...
    'Data'              ,fullfile(root,project,'Data'),...
    'Publications'      ,fullfile(root,project,'Publications'),...
    'originalPplData'   ,fullfile(root,project,'Data',experiment,...
                        'Data-People','Originals','Device'),...
    'editedPplData'     ,fullfile(root,project,'Data',experiment,...
                        'Data-People','Work In Progress','Edited Data'),...
    'originalEnvData'   ,fullfile(root,project,'Data',experiment,...
                        'Data-Enviroment','Originals','Device'),...
    'editedEnveData'    ,fullfile(root,project,'Data',experiment,...
                        'Data-Enviroment','Work In Progress','Edited Data'),...
    'peopleResults'     ,fullfile(root,project,'Data',experiment,...
                        'Data-People','Work In Progress','Analysis Results'),...
    'EnveResults'       ,fullfile(root,project,'Data',experiment,...
                        'Data-Enviroment','Work In Progress','Analysis Results'),...
    'peoplelogs'        ,fullfile(root,project,'Data',experiment,...
                        'Data-People','Originals','Logs'),...
    'Enviromentlogs'    ,fullfile(root,project,'Data',experiment,...
                        'Data-Enviroment','Originals','Logs'));
    
    names = fieldnames(paths);
    for iPaths = 1:numel(names)
        if ~exist(paths.(names{iPaths}),'dir')
           paths.(names{iPaths}) = []; 
        end
    end
end