function t = table(obj)
%TABLE Overloads table converter method
%   Detailed explanation goes here

varNames = {'Red','Green','Blue','Date','Label'};
t = table(...
    vertcat(obj.Red),...
    vertcat(obj.Green),...
    vertcat(obj.Blue),...
    vertcat(obj.Date),...
    {obj.Label}',...
    'VariableNames',varNames);

end

