function handels = createUserInterface()
% CREATEUSERINTERFACE will creat the GUI used to start and stop daysimeters
% handels = CREATEUSERINTERFACE() will generate all of the handels used to
% control the GUI used to start/stop/resume daysimeters and to download them.
%% Create the Window
handels = struct();
handels.head = figure('DockControl',   'off',...
           'MenuBar',       'none',...
           'Name',          'Daysimeter Start/Stop Hub',...
           'NumberTitle',   'off',...
           'ToolBar',       'None',...
           'units',         'Normalized',...
           'outerPosition', [.33,.33,.33,.33]);
%% Start up Interface
handels.daysimSearch = uibuttongroup(handels.head,...
    'Units',    'normalized',...
    'Position', [0,0,1,1],...
    'fontsize', 10,...
    'Visible','on');

handels.search.searchButtons = uibuttongroup(handels.daysimSearch,...
    'Units',    'normalized',...
    'Position', [.05,.05,.90,.60],...
    'title',    '',...
    'fontsize', 10);

handels.search.exit = uicontrol(handels.search.searchButtons,...
    'Units',    'normalized',...
    'Position', [.05,.05,.90,.40],...
    'String',   'Quit',...
    'callback', 'delete(gcbf)',...
    'fontsize', 12);
handels.search.search = uicontrol(handels.search.searchButtons,...
    'Units',    'normalized',...
    'Position', [.05,.55,.90,.40],...
    'String',   'Search',...
    'callback', 'daysimeter12.search(handels)',...
    'fontsize', 12);

handels.search.titleBlock = uicontrol(handels.daysimSearch,...
    'style',    'text',...
    'units',    'normalized',...
    'position', [.05,.80,.9,.15],...
    'string',   'Daysimeter Start Stop Hub',...
    'fontsize', 12);

handels.search.instructBlock = uicontrol(handels.daysimSearch,...
    'style',    'text',...
    'units',    'normalized',...
    'position', [.05,.70,.9,.15],...
    'string',   'Click Search to find Daysimeters',...
    'fontsize', 10);


%% Daysimeters found interface
handels.daysimFound = uibuttongroup(handels.head,...
    'Units',    'normalized',...
    'Position', [0,0,1,1],...
    'fontsize', 10,...
    'Visible','off');

handels.found.startStopButtons = uibuttongroup(handels.daysimFound,...
    'Units',    'normalized',...
    'Position', [.05,.05,.90,.60],...
    'title',    'Change Current Log',...
    'fontsize', 10);

handels.found.startbutton = uicontrol(handels.found.startStopButtons,...
    'Style',    'pushbutton',...
    'units',    'normalized',...
    'Position', [0.1 0.66 0.75 0.2],...
    'String',   'Start',...
    'callback', 'daysimeter12.startDaysimeters(handels)',...
    'fontsize', 10);

handels.found.stopbutton = uicontrol(handels.found.startStopButtons,...
    'Style',    'pushbutton',...
    'units',    'normalized',...
    'Position', [0.1 0.33 0.75 0.2],...
    'String',   'Stop and Download',...
    'callback', 'daysimeter12.stopDaysimeters(handels)',...
    'fontsize', 10);

handels.found.resumebutton = uicontrol(handels.found.startStopButtons,...
    'Style',    'pushbutton',...
    'units',    'normalized',...
    'Position', [0.1 0.01 0.75 0.2],...
    'String',   'Resume',...
    'callback', 'daysimeter12.resumeDaysimeters(handels)',...
    'fontsize', 10);

handels.found.titleBlock = uicontrol(handels.daysimFound,...
    'style',    'text',...
    'units',    'normalized',...
    'position', [.05,.80,.9,.15],...
    'string',   'Daysimeter Start Stop Hub',...
    'fontsize', 12);

handels.found.instructBlock = uicontrol(handels.daysimFound,...
    'style',    'text',...
    'units',    'normalized',...
    'position', [.05,.70,.9,.15],...
    'string',   'What would you like to do with these Daysimeters?',...
    'fontsize', 10);


end