function handels = createUserInterface()
% CREATEUSERINTERFACE will creat the GUI used to start and stop daysimeters
% handels = CREATEUSERINTERFACE() will generate all of the handels used to
% control the GUI used to start/stop/resume daysimeters and to download them.
%% Create the Window
handels = struct();
mp = get(groot,'monitorposition');
window = floor([.33*mp(1,3),.33*mp(1,4),.33*mp(1,3),.33*mp(1,4)]);
handels.head = figure('DockControl',   'off',...
           'MenuBar',       'none',...
           'Name',          'Daysimeter Start/Stop Hub',...
           'NumberTitle',   'off',...
           'ToolBar',       'None',...
           'units',         'pixel',...
           'Position',      window);
%% Start up Interface
handels.daysimSearch = uibuttongroup(handels.head,...
    'Units',    'pixel',...
    'Position', floor([0*window(3),0*window(4),1*window(3),1*window(4)]),...
    'fontsize', 10,...
    'Visible','on');
buttonGroup = floor([.05*window(3),.05*window(4),.90*window(3),.60*window(4)]);
handels.search.searchButtons = uibuttongroup(handels.daysimSearch,...
    'Units',    'pixels',...
    'Position', buttonGroup,...
    'title',    '',...
    'fontsize', 10);

handels.search.exit = uicontrol(handels.search.searchButtons,...
    'Units',    'pixel',...
    'Position', floor([.05*buttonGroup(3),.05*buttonGroup(4),.90*buttonGroup(3),.40*buttonGroup(4)]),...
    'String',   'Quit',...
    'callback', 'delete(gcbf)',...
    'fontsize', 12);
handels.search.search = uicontrol(handels.search.searchButtons,...
    'Units',    'pixel',...
    'Position', floor([.05*buttonGroup(3),.55*buttonGroup(4),.90*buttonGroup(3),.40*buttonGroup(4)]),...
    'String',   'Search',...
    'callback', 'daysimeter12.search(handels)',...
    'fontsize', 12);

handels.search.titleBlock = uicontrol(handels.daysimSearch,...
    'style',    'text',...
    'units',    'pixel',...
    'position', floor([.05*window(3),.80*window(4),.9*window(3),.15*window(4)]),...
    'string',   'Daysimeter Start Stop Hub',...
    'fontsize', 12);

handels.search.instructBlock = uicontrol(handels.daysimSearch,...
    'style',    'text',...
    'units',    'pixel',...
    'position', floor([.05*window(3),.70*window(4),.9*window(3),.15*window(4)]),...
    'string',   'Click Search to find Daysimeters',...
    'fontsize', 10);


%% Daysimeters found interface
handels.daysimFound = uibuttongroup(handels.head,...
    'Units',    'pixel',...
    'Position', floor([0*window(3),0*window(4),1*window(3),1*window(4)]),...
    'fontsize', 10,...
    'Visible',  'off');
buttonGroup = floor([.05*window(3),.05*window(4),.90*window(3),.60*window(4)]);
handels.found.startStopButtons = uibuttongroup(handels.daysimFound,...
    'Units',    'pixel',...
    'Position', buttonGroup,...
    'title',    'Change Current Log',...
    'fontsize', 10);

handels.found.startbutton = uicontrol(handels.found.startStopButtons,...
    'Style',    'pushbutton',...
    'units',    'pixel',...
    'Position', floor([0.1*buttonGroup(3), 0.66*buttonGroup(4), 0.75*buttonGroup(3), 0.2*buttonGroup(4)]),...
    'String',   'Start',...
    'callback', 'daysimeter12.startDaysimeters(handels)',...
    'fontsize', 10);

handels.found.stopbutton = uicontrol(handels.found.startStopButtons,...
    'Style',    'pushbutton',...
    'units',    'pixel',...
    'Position', floor([0.1*buttonGroup(3), 0.33*buttonGroup(4), 0.75*buttonGroup(3), 0.2*buttonGroup(4)]),...
    'String',   'Stop and Download',...
    'callback', 'daysimeter12.stopDaysimeters(handels)',...
    'fontsize', 10);

handels.found.resumebutton = uicontrol(handels.found.startStopButtons,...
    'Style',    'pushbutton',...
    'units',    'pixel',...
    'Position', floor([0.1*buttonGroup(3), 0.01*buttonGroup(4), 0.75*buttonGroup(3), 0.2*buttonGroup(4)]),...
    'String',   'Resume',...
    'callback', 'daysimeter12.resumeDaysimeters(handels)',...
    'fontsize', 10);

handels.found.titleBlock = uicontrol(handels.daysimFound,...
    'style',    'text',...
    'units',    'pixel',...
    'position', floor([.05*window(3),.80*window(4),.9*window(3),.15*window(4)]),...
    'string',   'Daysimeter Start Stop Hub',...
    'fontsize', 12);

handels.found.instructBlock = uicontrol(handels.daysimFound,...
    'style',    'text',...
    'units',    'pixel',...
    'position', floor([.05*window(3),.70*window(4),.9*window(3),.15*window(4)]),...
    'string',   'What would you like to do with these Daysimeters?',...
    'fontsize', 10);


end